baseURL = "https://sitradu.org/"
locale = "es-AR"
title = "SiTraDU — Conadu Histórica"
theme = "PaperMod"

# Paginación de las listas (noticias + enlaces combinados)
[pagination]
  pagerSize = 15

[params]
  description = "Sitio informativo del sindicato docente"
  env = "production"
  defaultTheme = "auto"
  disableSpecial1stPost = true
  mainSections = ["noticias", "enlaces"]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false

[taxonomies]
  category = "categories"

[[menu.main]]
  identifier = "categories"
  name = "Categorías"
  url = "/categories/"
  weight = 10

[params.homeInfoParams]
  Title = "Documentos · Noticias · Enlaces"
  Content = "Para los Trabajadores Docentes Universitarios de Entre Ríos"
  ImageLight = "/images/sitradu-logo-claro.png"
  ImageDark =  "/images/sitradu-logo-oscuro.png"
  
[[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/SITRADU"

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/sitradu/"